name: "tests"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  tests_timeout: "2h"
  golangci_lint_version: "v1.26"
jobs:
  validate:
    name: "Validate"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: tflint
        run: docker run --rm -v $(pwd):/data -t wata727/tflint
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_CLOUD_KEYFILE_JSON }}
          export_default_credentials: true
      - run: gcloud info

      - name: "go vet"
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: ${{ env.golangci_lint_version }}

      - name: "go test"
        run: go test -timeout ${{ env.tests_timeout }} ./...